LITRES-103 intermediate commit
LitresNET/Literes pull request #10
Opened 2024-03-24 07:58 UTC by schwrmt

2024-03-24 18:07 UTC, coldezzt commented on backend/src/Services.Main/Abstractions/IRepository.cs
> +    //интерфейса? Мне кажется, так будет лучше.
Уже реализовано у Айсылу, как смёржим можешь стянуть

2024-03-24 18:07 UTC, coldezzt commented
Как я понял, ещё почти ничего не реализовано, проверять не стал

2024-03-24 18:17 UTC, schwrmt commented on backend/src/Services.Main/Abstractions/IRepository.cs
> +    //интерфейса? Мне кажется, так будет лучше.
узас

2024-03-24 18:18 UTC, schwrmt commented
Айсылу попросила сделать коммит промежуточный. Там уже все переписано на самом деле. Я не могу прост пока протестить никак

2024-03-25 19:23 UTC, coldezzt reviewed
Нет тестов, в остальном косметические изменения. Всё ок

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Configurations/Mapping/BookMapperProfile.cs
> +        CreateMap<BookCreateRequestDto, Book>(); //That's correct
ладно, если уж правильно

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Controllers/RegistrationController.cs
> +using Microsoft.AspNetCore.Mvc.Filters;
Кажись не все юзинги тут нужны

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Dto/Requests/UserRegistrationDto.cs
> +    [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$")]
жесть

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Repositories/PublisherRepository.cs
> +        return result.Entity;;
лишняя точка с запятой

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Repositories/PublisherRepository.cs
> +        return result.Entity;;
тоже

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Repositories/UserRepository.cs
> +        return result.Entity;;
снова

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Services/RegistrationService.cs
> +public class RegistrationService(IUserRepository userRepository, IPublisherRepository publisherRepository, IUnitOfWork unitOfWork, UserManager<User> userManager) : IRegistrationService
разбить на несколько строчек

2024-03-25 19:23 UTC, coldezzt commented on backend/src/Services.Main/Services/RegistrationService.cs
> +        throw new NotImplementedException();
а где

2024-03-25 19:37 UTC, coldezzt requested changes
Посмотри предыдущие комменты и можно будет мёржить

2024-03-25 20:05 UTC, schwrmt commented on backend/src/Services.Main/Dto/Requests/UserRegistrationDto.cs
> +    [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$")]
Регулярное выражение для пароля длиной от 8 символов, содержащего цифры, заглавные и строчные буквы английского выражения и спецсимволы (хотя бы по 1)

2024-03-25 21:27 UTC, schwrmt commented on backend/src/Services.Main/Controllers/RegistrationController.cs
> +using Microsoft.AspNetCore.Mvc.Filters;
Все юзинги важны, все юзинги нужны

2024-03-25 21:27 UTC, schwrmt commented on backend/src/Services.Main/Abstractions/IRepository.cs
> +    //интерфейса? Мне кажется, так будет лучше.
Реализовал под свои 2 добавленных репозитория, чтобы потом не переписывать.

2024-03-25 21:28 UTC, schwrmt commented on backend/src/Services.Main/Repositories/PublisherRepository.cs
> +        return result.Entity;;
убрал

2024-03-25 21:28 UTC, schwrmt commented on backend/src/Services.Main/Repositories/PublisherRepository.cs
> +        return result.Entity;;
убрал

2024-03-25 21:29 UTC, schwrmt commented on backend/src/Services.Main/Repositories/UserRepository.cs
> +        return result.Entity;;
убрал

2024-03-26 07:50 UTC, schwrmt commented on backend/src/Services.Main/Services/RegistrationService.cs
> +        throw new NotImplementedException();
Реализовал

2024-03-26 08:42 UTC, schwrmt commented on backend/src/Services.Main/Repositories/ContractRepository.cs
> +        var result = appDbContext.Contract.Remove(contract);
исправил

2024-03-26 09:02 UTC, coldezzt approved these changes
Nice

2024-03-26 09:03 UTC, merged