Litres-100 order creation service
LitresNET/Literes pull request #36
Opened 2024-04-11 20:10 UTC by Who-car

2024-04-13 15:22 UTC, coldezzt requested changes
1) Почему изменения по задаче задели фронт?
2) Почему нет тестов на сервис?

2024-04-13 15:22 UTC, coldezzt commented on backend/src/Litres.Main/Controllers/OrderController.cs
> +        HttpContext.Request.Headers.Append(HeaderNames.Origin, "http://localhost:5032/pay");
можно упростить до просто Request. ...

2024-04-13 15:22 UTC, coldezzt commented on backend/src/Litres.Main/Controllers/OrderController.cs
> +    }
Содержимое можно заменить на:
```cs
await orderService.ConfirmOrderAsync(orderId, isSuccess);
return Ok(isSuccess 
   ? "Transaction committed\nNew order created" 
   : "Transaction rollback\nCouldn't create order"
   );
```

2024-04-13 15:22 UTC, coldezzt commented on backend/src/Litres.Main/Services/OrderService.cs
> +            [ y => y.OrderedBooks ]);
Мой райдер не распознает это, так что поверю на слово)

2024-04-14 11:13 UTC, Who-car commented on backend/src/Litres.Main/Services/OrderService.cs
> +            [ y => y.OrderedBooks ]);
это collection expression, видимо недавний прикол от .net 8 и последней версии rider'а)

2024-04-14 15:08 UTC, Who-car commented
в измененных файлах не вижу изменений по фронту, возможно ты имел ввиду сервис оплаты
логику взаимодействия со сторонним сервисом пришлось подкорректировать, т.к. в первоначальном варианте реализации сервиса оплаты не было учтено, что при редиректе невозможно передать комплексные данные

2024-04-15 15:48 UTC, merged