litres-63 fix(asp-app) refactor infrastructure
LitresNET/Literes pull request #6
Opened 2024-03-22 15:31 UTC by Who-car

внесла правки с последнего созвона

2024-03-23 13:33 UTC, Who-car commented
закончена задача litres-62 - обновление данных по книге

2024-03-24 18:03 UTC, coldezzt requested changes
Лайк за код

2024-03-24 18:03 UTC, coldezzt commented on backend/tests/Tests.Unit/MainService/Services/BookServiceTests/UpdateBook.cs
> +        var service = new BookService(
Как я понял, настройки выше полностью сбрасывают все настройки репозиториев и ты всё равно на основе приватных переменных каждый раз создаёшь этот объект. Возможно ли сделать его приватным свойством? У него будет переопределён метод get и вот он как раз будет возвращать новый собранный объект BookService

2024-03-26 07:16 UTC, Who-car commented on backend/src/Services.Main/Models/Book.cs
> -    public List<Request>? Requests { get; set; }
Книга по идее не должна знать о том, какие над ней манипуляции выполняют сверху, ей достаточно знать в каком она сейчас состоянии (доступна, не доступна). А связь o-t-m в бд все равно есть
Вообще в PR, где есть сидированная бд (он случайно попал в PR к верстке, написала в чате), тоже много изменений, которые по-хорошему тоже надо согласовать

2024-03-26 07:27 UTC, Who-car commented on backend/src/Services.Main/Services/BookService.cs
> +            };
Я вроде постаралась описать этот кейс в комментарии, но видимо у меня плохо получилось
Когда мы хотим изменить данные по книге (пусть не сам текст, но любые метаданные), то пока запрос на изменение не одобрен, книга недоступна. А это минус деньги заказчику. Поэтому когда мы вносим изменения в книгу, мы создаем в бд новую запись (с новым id и прочими новыми данными), и эту новую книгу делаем недоступной. После того, как запрос одобрят мы удаляем старую книгу (со старым ID) и делаем доступной новую книгу. Если запрос не одобрят - удаляем новую книгу и все. Запрос должен хранить ссылки на обе версии книги, чтобы решить какую удалить, а какую оставить.
Возможно стоит переименовать в OldBookId...

2024-03-26 07:27 UTC, Who-car commented on backend/src/Services.Main/Models/Request.cs
> +    public long UpdatedBookId { get; set; }
ответила там же

2024-03-26 07:34 UTC, coldezzt commented on backend/src/Services.Main/Services/BookService.cs
> +            };
Нам в этом случае тогда придётся менять всех коментарии (менять id книги в них) и пользователей (менять лайки)
Хотя можно перенаправление сделать или просто скопировать данные с одной книги для другой

2024-03-26 07:38 UTC, Who-car commented on backend/tests/Tests.Unit/MainService/Services/BookServiceTests/UpdateBook.cs
> +        var service = new BookService(
это звучит здраво, но я не представляю себе, как можно локальную переменную метода вынести в переопределенный геттер/сеттер мока репозитория
Потому что, например, _bookRepositoryMock в кейсе DefaultBook_ReturnsRequestUpdate на метод GetByIdAsync возвращает заглушку книги, а в кейсе NotExistingBook_ThrowsBookNotFoundException возвращает null. Переопределить сеттер, чтобы он принимал возвращемый объект? Несовпадение типов + не читаемо. В геттере определить входные параметры, а возвращаемый объект описывать локально в методах? Опять таки не читаемо, потому что в разные места рассовываем входные и выходные аргументы

в общем я только за, мне самой не нравится в каждом методе мок репозитория описывать, но я не представлю как это можно сделать. Если есть идеи, я это сделаю, если нет - тогда предлагаю оставить так, как есть

2024-03-26 07:52 UTC, coldezzt commented on backend/tests/Tests.Unit/MainService/Services/BookServiceTests/UpdateBook.cs
> +        var service = new BookService(
Вот что я предлагаю:
![изображение](https://github.com/LitresNET/Literes/assets/61345590/1d71b55d-6d94-4b97-88c5-67cecc831bad)
И вот во что превращаются BookService в каждом тесте:
![изображение](https://github.com/LitresNET/Literes/assets/61345590/5a2929c9-2a59-4b3e-9f07-a1335766d32c)

Заполнение вручную каждого репозитория - от этого не избавишься(

2024-03-26 08:39 UTC, coldezzt approved these changes
Найс

2024-03-26 08:41 UTC, merged