litres-111 feature(review-components) add change and delite methods
LitresNET/Literes pull request #60
Opened 2024-04-21 13:31 UTC by schwrmt

2024-04-21 13:34 UTC, schwrmt commented on backend/src/Litres.Main/Controllers/ReviewController.cs
> +using Microsoft.AspNetCore.Http.HttpResults;
случайно появилось, убрать

2024-04-21 13:36 UTC, schwrmt commented
Добавил так же пару TODO, чтобы сразу помечать то, что нужно будет изменить при рефакторе. Некоторые TODO относятся ко всем идентичным строкам кода (например где проверка на claims), но не дублированы чтобы не засорять код. Тесты не писал, т.к. в задаче не требовалось (да и хз че там тестить)

2024-04-22 08:25 UTC, coldezzt requested changes
Добавь тесты на выброс исключений

2024-04-29 21:49 UTC, schwrmt commented
Все тесты написаны. Добавил в метод UpdateReview проверку на наличие такого Review для выброса кастомной EntityNotFoundException. (правда из контроллера все равно приходит 100% существующий ревью, ибо в этом же контроллере он и так берётся через GetReviewById и проверяются айдишники пользователя). Строку из новых тестов на проверку вызова UnitOfWork.SaveChangesAsync думаю надо добавить в каждый тест, который относится к методу, вносящему изменения в бд (соотсвественно который и обязан вызывать SaveChangesAsync)

2024-04-29 21:57 UTC, schwrmt commented
Также прошу обратить внимание на изменения в [ApplicationDbContext.cs](https://github.com/LitresNET/Literes/pull/60/files#diff-51e92950961dbff6ff106292a29fad15b86b970114c3cbb2990d1dbe8f77c4b4) (их можно убрать, ведь идентичный функционал выполнет индекс) и индекс в классах Review и ReviewLike. Добавлен он был исходя из требований бизнес логики и позволяет даже при неправильном написании метода сервиса (один из которых я исправлял в этом же пр) не допустить добавления его в бд, что обезопасит её и сразу укажет на ошибку в реализации логики того или иного функционала. Поэтому, считаю, что подобные индексы (которые используются не только для проверки на уникальность) должны появиться и в других классах в процессе рефакторинга. Для индексов также потом потребуются новые миграции.

2024-05-09 15:42 UTC, coldezzt approved these changes

2024-05-09 15:42 UTC, merged